<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="WFE.Test" Key="002400000480000094000000060200000024000052534131000400000100010045fcbdddf3699f7c3607dab0bdfa35be6d8494080f3b3c8eb0960143f39a394a9128f20245667b15859c6a02c941a4e6c25331324b98f38df7b87bb564393e083c23015e0d6794e457faf2c7450b7791f19bfac4b52c89ba0089eafdf973dc942d43903b1813d31574cc0770291d02c821696af9d9d177950a5ed511337ee8c0" />
  </ItemGroup>
  <PropertyGroup>
    <HaleyProject Condition="'$(HaleyProject)' == ''">$(MSBuildProjectDirectory)\..\..</HaleyProject>
  </PropertyGroup>
  <Import Project="$(HaleyProject)\HaleyProject\Haley.Source.Props" />
  <Import Project="$(HaleyProject)\HaleyProject\Haley.Version.Props" />
  <Import Project="$(HaleyProject)\HaleyProject\Haley.Paths.Props" />
  <Import Project="Database\Database.Source.props" />
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
    <RootNamespace>Haley</RootNamespace>
    <AssemblyName>Haley.Flow.Engine</AssemblyName>
    <SignAssembly>True</SignAssembly>
    <IsPackable>true</IsPackable>
    <AssemblyOriginatorKeyFile>..\..\HaleyProject\HaleyProject.snk</AssemblyOriginatorKeyFile>
    <PackageIcon>Haley.png</PackageIcon>
    <Version>$(HaleyFlowEngineVersion)</Version>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReleaseNotes>Pilot release</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>$(ProjectBaseUrl)Flow.Engine</PackageProjectUrl>
    <RepositoryUrl>$(ProjectBaseUrl)Flow.Engine</RepositoryUrl>
    <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
    <Description>WorkFlow Engine from Haley Libraries</Description>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\HaleyLog\Haley.png" Link="Haley.png">
      <PackagePath></PackagePath>
      <Pack>True</Pack>
    </None>
    <None Include="Models\WorkFlowAckRef.cs" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Scripts\" />
  </ItemGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <WarningLevel>2</WarningLevel>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <Choose>
    <When Condition="Exists('$(HaleyHelpersDBProj)')">
      <ItemGroup>
        <ProjectReference Include="$(HaleyHelpersDBProj)">
          <Name>HaleyHelpersDB</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Haley.Helpers.DB" Version="$(HaleyHelpersDBVersion)" />
      </ItemGroup>
    </Otherwise>
  </Choose>
</Project>
